services:
  api:
    image: ${DOCKERHUB_USER}/listenroom-api:latest
    network_mode: host
    volumes:
      - audio-cache:/app/audio-cache
      - ./cookies.txt:/app/cookies.txt
    environment:
      YTDLP_PROXY: socks5://127.0.0.1:40000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  web:
    image: ${DOCKERHUB_USER}/listenroom-web:latest
    ports:
      - '3000:3000'
    environment:
      API_URL: http://localhost:4000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  audio-cache:
